<?php
	$this->title = "My Books";
	$this->headTitle($this->title);
?>
<?php if($this->auth->isAllowed('book', 'add')): ?>
<p>
<a href="<?php echo $this->url(array('controller'=>'book','action'=>'add'));?>">Add new book</a>
</p>
<?php endif; ?>
<table>
	<tr>
		<th>Title</th>
		<th>Author</th>
		<th>Status</th>
		<th>&nbsp;</th>
		</tr>
		<?php if (count($this->books)): ?>
			<?php foreach($this->books as $book) : ?>
			<tr>
				<td><?php echo $this->escape($book['title']);?></td>
				<td><?php echo $this->escape($book['author']);?></td>
				<td>
					<?php 
						if($book['status'] == 0)
						echo "available";
						else
						echo "not available";
					?>
				</td>
				<td>
					
					<?php if($this->auth->isAllowed('book', 'edit')): ?>
					<a href="<?php echo $this->url(array('controller'=>'book','action'=>'edit', 'id'=>$book['id']));?>">Edit</a>&nbsp;&nbsp;
					<?php endif; ?>
					
					<?php if($this->auth->isAllowed('book', 'delete')): ?>
					<a href="<?php echo $this->url(array('controller'=>'book','action'=>'delete', 'id'=>$book['id']));?>">Delete</a>&nbsp;&nbsp;
					<?php endif; ?>
					
					<?php if($book['status'] == 0): ?>
						<?php if($this->auth->isAllowed('book', 'loan')): ?>
						<a href="<?php echo $this->url(array('controller'=>'book','action'=>'loan', 'id'=>$book['id']));?>">Loan</a>
						<?php endif; ?>
					<?php else: ?>
						<?php if($this->auth->isAllowed('book', 'return')): ?>
						<a href="<?php echo $this->url(array('controller'=>'book','action'=>'return', 'id'=>$book['id']));?>">Return</a>
						<?php endif; ?>
					<?php endif; ?>

				</td>
			</tr>
			<?php endforeach; ?>
		<?php else: ?>
			<tr>
				<td colspan="4">No books available.</td>
			</tr>
		<?php endif; ?>
			<tr>
				<td colspan="4">
				<?php 
					echo $this->paginationControl($this->books,'Sliding','/partials/my_pagination_control.phtml'); 
				?>
				</td>
			</tr>
</table>
<p>To log out <a href='<?php echo $this->url(array('controller'=>'user', 'action'=>'logout'), null,true); ?>'>click here</a></p>
