<?php
	$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle('Library System');
	echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/layout.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css'); ?>
	<?php echo $this->jQuery(); ?>
</head>
<body>


<div id="pageWrapper">
	<div id="header">
	<h1>Library System</h1>
	</div>
	
	<div id="nav">&nbsp;</div>
	
	<div id="sidebar">

	</div>
	
	<div id="main">
		<?php echo $this->layout()->content?>&nbsp;
	</div>
	
	<div id="footer">
	<p><em>Powered by the Zend Framework</em></p>
	</div>
</div>
</body>
</html>